#!/usr/bin/env python

"""OpenVPN status parser

Usage:
    openvpn-status-parser <filename>...  [--json]

"""

import os.path
import pprint
import sys

import docopt
import openvpn_status_parser


def main():
    arguments = docopt.docopt(__doc__, version='OpenVPN status parser')
    output_json = arguments['--json']

    for filename in arguments["<filename>"]:
        if not os.path.exists(filename):
            print("File '%s' does not exist. Exiting." % filename)
            return 1
        parser = openvpn_status_parser.OpenVPNStatusParser(filename)

        if output_json:
            print(parser.json)
        else:
            print("=" * 79)
            print(filename)
            print("-" * 79)
            print("Connected clients")
            pprint.pprint(parser.connected_clients)
            print("-" * 79)
            print("Routing table")
            pprint.pprint(parser.routing_table)
            print("-" * 79)
            print("Additional details")
            pprint.pprint(parser.details)
    return 0


if __name__ == '__main__':
    sys.exit(main())
